DisapeardPeople.MVC/Controllers/AdministratorController.cs
using DisapeardPeople.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace DisapeardPeople.MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdministratorController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        public AdministratorController(UserManager<UserModel> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = _userManager.Users;
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListUsers");
            }
        }
    }
}

DisapeardPeople.MVC/Controllers/DisappearPersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DisapeardPeople.MVC.Data;
using DisapeardPeople.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using DisapeardPeople.MVC.Data.Enum;
using Microsoft.Extensions.Hosting;

namespace DisapeardPeople.MVC.Controllers
{
    public class DisappearPersonsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public DisappearPersonsController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: DisappearPersons
        public async Task<IActionResult> Index(Gender? genderFilter)
        {
            var disappearPersons = _context.DisappearPerson.AsQueryable();

            if (genderFilter.HasValue)
            {
                disappearPersons = disappearPersons.Where(x => x.Gender == genderFilter.Value);
            }

            return View(await disappearPersons.ToListAsync());
        }

        // GET: DisappearPersons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DisappearPerson == null)
            {
                return NotFound();
            }

            var disappearPerson = await _context.DisappearPerson
                .FirstOrDefaultAsync(m => m.Id == id);
            if (disappearPerson == null)
            {
                return NotFound();
            }

            return View(disappearPerson);
        }

        // GET: DisappearPersons/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: DisappearPersons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,FirstName,Surname,Age,Height,City,ImageFile,DisappearDate,Province,Gender")] DisappearPerson disappearPerson)
        {
            //Zapisz zdjęcie do wwwroot/image
            string wwwRootPath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(disappearPerson.ImageFile.FileName);
            string extension = Path.GetExtension(disappearPerson.ImageFile.FileName);
            disappearPerson.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path = Path.Combine(wwwRootPath + "/Image", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await disappearPerson.ImageFile.CopyToAsync(fileStream);
            }
            _context.Add(disappearPerson);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: DisappearPersons/Edit/5
        [Authorize(Roles ="admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DisappearPerson == null)
            {
                return NotFound();
            }

            var disappearPerson = await _context.DisappearPerson.FindAsync(id);
            if (disappearPerson == null)
            {
                return NotFound();
            }
            return View(disappearPerson);
        }

        // POST: DisappearPersons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,Surname,Age,Height,City,ImageFile,DisappearDate,Province,Gender")] DisappearPerson disappearPerson)
        {
            if (id != disappearPerson.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (disappearPerson.ImageFile != null && disappearPerson.ImageFile.Length > 0)
                    {
                        string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "Image");
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + disappearPerson.ImageFile.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await disappearPerson.ImageFile.CopyToAsync(stream);
                        }
                        disappearPerson.Image = uniqueFileName;
                    }

                    _context.Update(disappearPerson);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisappearPersonExists(disappearPerson.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(disappearPerson);
        }

        // GET: DisappearPersons/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DisappearPerson == null)
            {
                return NotFound();
            }

            var disappearPerson = await _context.DisappearPerson
                .FirstOrDefaultAsync(m => m.Id == id);
            if (disappearPerson == null)
            {
                return NotFound();
            }

            return View(disappearPerson);
        }

        // POST: DisappearPersons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var disappearPerson = await _context.DisappearPerson.FindAsync(id);

            //usuwanie img z wwwroot/Image
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Image", disappearPerson.Image);
            if(System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            _context.DisappearPerson.Remove(disappearPerson);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DisappearPersonExists(int id)
        {
          return (_context.DisappearPerson?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DisapeardPeople.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DisapeardPeople.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DisapeardPeople.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="DisappearPersons" asp-action="Index">Osoby zaginione</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DisappearPersons" asp-action="Index">Lista osób zaginionych</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DisappearPersons" asp-action="Create">Dodaj osobę zaginioną</a>
                            </li>

                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("admin"))
                            {
                             <li class="nav-item ">
                                <a class="nav-link text-dark " asp-area="" asp-controller="Administrator" asp-action="ListUsers">Zarządzaj użytkownikami</a>
                            </li>
                            }
                            <li class="nav-item ">
                                <a class="nav-link text-dark " asp-area="" asp-controller="Account" asp-action="Logout">Wyloguj</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item ">
                                <a class="nav-link text-dark " asp-area="" asp-controller="Account" asp-action="Login">Logowanie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Rejestracja</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DisapeardPeople
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>